// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error)
	GetAllAccounts(ctx context.Context, arg GetAllAccountsParams) ([]Account, error)
	GetAllEntriesByAccountId(ctx context.Context, arg GetAllEntriesByAccountIdParams) ([]Entry, error)
	GetAllTransferByAccounts(ctx context.Context, arg GetAllTransferByAccountsParams) ([]Transfer, error)
	GetEntry(ctx context.Context, id uuid.UUID) (Entry, error)
	GetTransfer(ctx context.Context, id uuid.UUID) (Transfer, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
